kordamp/kordamp-gradle-plugins

- subprojects/guide/src/docs/asciidoc/plugins/licensing-gradle-plugin.adoc
org.kordamp.gradle.javadoc => org.kordamp.gradle.licensing
> Fix a typo

- subprojects/guide/src/docs/asciidoc/project-structure.adoc
Lines setting `rootProject.name` are already present in the "lower-level" code snippets that are above the snippets edited here.
Besides, tab names `settings.gradle(.kts)` suggest these are complete settings files, and without `rootProject.name = ...` they seem incomplete.
> Add lines setting root project name in sample settings.gradle(.kts)

- plugins/base-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/base/plugins/Plugin.groovy
Fixes #132.
Changed `Plugin.merge` so that `setId` / `setImplementationClass` are called only when `id` / `implementationClass` can change.
> [base] Fixed org.kordamp.gradle.plugin.base.plugins.Plugin.merge

- subprojects/guide/src/docs/asciidoc/project-structure.adoc
Groovy version uses [`eachDir`](http://docs.groovy-lang.org/latest/html/groovy-jdk/java/io/File.html#eachDir(groovy.lang.Closure)) which visits only child directories. Kotlin's [`walkTopDown()`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/walk-top-down.html) visits an entire tree unless [max depth](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/-file-tree-walk/max-depth.html) is specified.
> Add `maxDepth(1)` to `walkTopDown()`

- subprojects/guide/src/docs/asciidoc/plugins/project-gradle-plugin.adoc
`org.kordamp.gradle.project` plugin applies `org.kordamp.gradle.jacoco`, but it's not documented.
> Document applying org.kordamp.gradle.jacoco plugin

- plugins/plugin-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/plugin/PluginPlugin.groovy
`PluginPlugin` should apply `BasePlugin`, as per [spec](https://aalmiray.github.io/kordamp-gradle-plugins/#_org_kordamp_gradle_plugin).
> [Plugin] Apply BasePlugin if missing

- plugins/base-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/base/plugins/Javadoc.groovy
When `java-library` plugin is applied, `compile` configuration is superseded by `api` configuration: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation
> [Javadoc] Add 'api' configuration to DEFAULT_CONFIGURATIONS for AutoLinks

- plugins/apidoc-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/apidoc/ApidocPlugin.groovy
- plugins/javadoc-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/javadoc/JavadocPlugin.groovy
Before the fix, the following was set as Javadoc options:
```
-Xdoclint:none '-quiet'
```
After the fix, it'll be:
```
-Xdoclint:none
-quiet
```
> Fix setting `-Xdoclint:none` and `-quiet` options for Javadoc

- subprojects/guide/src/docs/asciidoc/project-structure.adoc
This PR simplifies the evaluation of the property `release` in the Kotlin DSL example in the guide.
The simplified version relies on Kotlins `toString` method that is able to return "null" when called on objects that are null and the extension function `toBoolean` that will convert string "true" (case-insensitively) to the boolean `true` and any other string value to boolean `false`.
> Simplify configuration example for Kotlin DSL for release

- plugins/functionaltest-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/functionaltest/FunctionalTestPlugin.groovy
- plugins/integrationtest-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/integrationtest/IntegrationTestPlugin.groovy
- subprojects/guide/src/docs/asciidoc/plugins/functionaltest-gradle-plugin.adoc
- subprojects/guide/src/docs/asciidoc/plugins/integrationtest-gradle-plugin.adoc
This PR reintroduces the option with the `IntegrationTestPlugin` and the `FunctionalTestPlugin` to run test classes within `src\integration-test\kotlin`.
Without it, integration tests written in kotlin are only executed if they reside in `src\integration-test\java` (and alike for functional tests)
Since we do not have a kotlin specific plugin within the kordamp gradle plugin suite, I based the decision of whether to apply the source set modifications on the presence of the stock kotlin gradle plugin. This may be revised when - and if - there will be a kotlin specific plugin within the kordamp suite.
> Improve support for integration/functional test written in kotlin

- plugins/functionaltest-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/functionaltest/FunctionalTestPlugin.groovy
- plugins/integrationtest-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/integrationtest/IntegrationTestPlugin.groovy
Potentially resolves #189
I have the impression that the `IdeaPlugin` already correctly resolves and integrates the new source set provided by the `IntegrationTestPlugin` and the `FunctionalTestPlugin` and does not need the additional configuration.
If I'm missing something (I probably do), we should make sure not to directly access the respective plugins and hence prevent IntelliJ from throwing the following exception
```
Resolving configuration 'integrationTestImplementation' directly is not allowed.
```
> Remove the IdeaPlugin based configuration for integration/functional tests to avoid an exception in IntelliJ

- plugins/detekt-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/detekt/DetektPlugin.groovy
DetektPlugin should be enabled for project with plugin `kotlin-base`, not `java-base`.
Merging this PR successfully builds my current PR https://github.com/ursjoss/kordamp-gradle-test-suite/pull/1 (tested locally)
> Fix detektPlugin: Apply detekt to projects with plugin kotlin-base (not java-base)

- docs/guide/src/docs/asciidoc/plugins/detekt-gradle-plugin.adoc
- plugins/base-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/base/plugins/Detekt.groovy
- plugins/detekt-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/detekt/DetektPlugin.groovy
This PR adds the configuration parameter `failFast` (with a default false).
Depends on PR #251 to be merged beforehand.
> Detekt: configuration Parameter failFast

- docs/guide/src/docs/asciidoc/plugins.adoc
- docs/guide/src/docs/asciidoc/plugins/sonar-gradle-plugin.adoc
- docs/guide/src/docs/asciidoc/project-dsl.adoc
- plugins/base-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/base/plugins/Sonar.groovy
- plugins/sonar-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/sonar/SonarPlugin.groovy
* Documentation: First draft - needs a thorough review and most likely adjustments
* Plugin amendments
* `ignoreFailures` does not require explicit merging (`AbstractQualityFeature.merge` does it already)
* Activate `configProperties`, so it is passed to sonar
* configured some additional sonar-properties, derived from `config.info`, only apply them if they have not been configured otherwise (e.g. through `configProperties`)
> SonarPlugin Documentation (first draft) + activation of configProperties

- docs/guide/src/docs/asciidoc/plugins/licensing-gradle-plugin.adoc
- docs/guide/src/docs/asciidoc/plugins/sourcehtml-gradle-plugin.adoc
Fixes wrong interpretation of the ant-style patterns in 
- licensing-gradle-plugin
- source-html-gradle-plugin
Patterns like ```'**/*.java,**/*.groovy'``` turned out as ```'/.java,/.groovy'```
Note: I was considering also including a note that the source-html plugin only works with java or groovy code (but not with kotlin or scala, I guess), but I refrained from it to not pollute the PR.
> Fix ant-patterns in guide

- plugins/buildinfo-gradle-plugin/buildinfo-gradle-plugin.gradle
Related to #267
temporary downgrade until we get a nemrose/versioning release >2.12.0 pulling in grgit-4.0.1
> [267] - temmporarily downgrade version plugin to 2.11.0

- docs/guide/src/docs/asciidoc/plugins/guide-gradle-plugin.adoc
- plugins/guide-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/guide/GuideExtension.groovy
- plugins/guide-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/guide/GuidePlugin.groovy
- plugins/kotlindoc-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/kotlindoc/KotlindocPlugin.groovy
The task `aggregateKotlindocHtml` did not actually process the (correctly created) kotlindoc of the individual submodules. Therefore the aggregated kotlindoc was empty.
This PR fixes this and also unhances the guide plugin to process kotlindoc (in a similar manner to groovydoc) and allows to publish it to e.g. the `gh-pages` branch.
I still struggle with two aspects getting my configuration right (assuming it's a configuration issue on my side). I have created a reproducer project and would be grateful for some guidance. I pollute this PR, as the reproducer currently only works with the changes in this PR. However, if you prefer, I am perfectly willing to open a dedicated issue for that once the guide aggregation is working correctly. …
> [Kotlindoc] - fix aggregation of kotlindoc for multi-module project

- docs/guide/src/docs/asciidoc/plugins/guide-gradle-plugin.adoc
- plugins/guide-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/guide/GuidePlugin.groovy
Resolves #262 
- Guide: Explicitly mention the location of the `imagesDir` (`src/docs/resources/images`)
- initGuide: Create the `imagesDir` so it can be found more easily even without consulting the guide
- initGuide: Define `magesdir` and `includedir` for IntelliJ to be able to resolve them
> [Guide] - Improve Documentation & initGuide

- .github/workflows/build.yml
I'm not sure if the build creates aggregate reports but if it does then this will crate a bundle on failure
> bundle reports after failure

- plugins/jacoco-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/jacoco/JacocoPlugin.groovy
- plugins/jar-gradle-plugin/src/main/groovy/org/kordamp/gradle/plugin/jar/JarPlugin.groovy
The Jacoco and Jar plugins were still using `create` instead of `register`
> Switched from creating tasks to register for Jacoco and Jar plugins

- docs/guide/src/docs/asciidoc/plugins/licensing-gradle-plugin.adoc
Hi there:
Licensing plugin docs mentioned OVERWRITE as mergeStrategy option, but applying plugin it complained with:
```
* What went wrong:
A problem occurred evaluating root project 'matter'.
> No enum constant org.kordamp.gradle.plugin.base.plugins.MergeStrategy.OVERWRITE
```
Checking source code I realized it should be **OVERRIDE** instead of **OVERWRITE**.
Cheers
Mario
> fix: honoring MergeStrategy in docs, change OVERWRITE -> OVERRIDE
